// ui/src/dash/firstrun.jsx
// hal0 dashboard — FirstRun (bundle picker, confirmation, progress)
//
// Phase B1: bundles + per-model downloads read from real hooks where
// available. Hardware detection (RAM / NPU / disk) still uses
// HAL0_DATA.host because /api/hardware lands separately; flip when
// useHardware is universally cheap.

import { useCuratedBundles, useFirstRunInstall, useFirstRunComplete } from '@/api/hooks/useFirstRun'
import { useHardware } from '@/api/hooks/useHardware'

const { useState: useStateF } = React;

// ─── Bundle picker (state 1) ───
function FirstRunPicker({ onPick, onSkip, layout }) {
  // Phase B1: live curated bundles + hardware detection. Fall through
  // to the static fixtures when either query hasn't returned yet, so
  // FirstRun renders fully on a cold boot.
  const bundlesQuery = useCuratedBundles();
  const hwQuery = useHardware();
  const bundles = bundlesQuery.data?.bundles ?? HAL0_DATA.bundles;
  const ramDetected = hwQuery.data?.ram?.total ?? HAL0_DATA.host.ram.total;
  // Recommended = highest tier whose minimum ≤ detected
  const fitTiers = bundles.filter(b => b.ram <= ramDetected);
  const recId = fitTiers.length ? fitTiers[fitTiers.length - 1].id : null;

  return (
    <div className="fr-inner">
      <div className="fr-head">
        <div className="fr-eyebrow"><span className="blip" />FirstRun · install</div>
        <h1 className="fr-title">Welcome to <span className="accent">hal0</span></h1>
        <p className="fr-lede">Pick a starting configuration. You can customise any slot later — or skip and configure manually.</p>
        <div className="fr-detect">
          <span className="seg"><span className="k">RAM</span><b>128 GB</b> unified</span>
          <span className="seg"><span className="k">GPU</span><b>Strix Halo</b> gfx1151</span>
          <span className="seg"><span className="k">NPU</span><b>XDNA2</b><span className="ok">●</span></span>
          <span className="seg"><span className="k">disk</span><b>412 GB</b> free</span>
        </div>
      </div>

      {layout === "table" ? (
        <BundleTable bundles={bundles} recId={recId} onPick={onPick} ram={ramDetected} />
      ) : (
        <BundleGrid bundles={bundles} recId={recId} onPick={onPick} ram={ramDetected} />
      )}

      <h3 className="fr-section-label" style={{marginTop: 28}}>Pre-built kits</h3>
      <div className="kit">
        <div className="kit-main">
          <div className="kit-eyebrow">AMD-curated · vendor-blessed</div>
          <div className="kit-name">LMX-Omni-52B-Halo</div>
          <div className="kit-spec">≥ 100 GB unified RAM Strix Halo · NPU trio · 4 slots ready out of the box</div>
          <div className="kit-models">
            <span className="chip">Qwen3.6-35B</span>
            <span className="chip">Whisper-Large</span>
            <span className="chip">kokoro</span>
            <span className="chip">Flux-2-Klein-9B</span>
          </div>
        </div>
        <div className="kit-side">
          <div className="sz mono">~75<span className="u">GB</span></div>
          <button className="btn lg" onClick={() => onPick("max")}>Install LMX kit</button>
        </div>
      </div>

      <div className="fr-skip-row">
        <button className="fr-skip" onClick={onSkip}>Skip — configure manually</button>
      </div>
    </div>
  );
}

function BundleGrid({ bundles, recId, onPick, ram }) {
  return (
    <div className="tiers">
      {bundles.map(b => {
        const fits = b.ram <= ram;
        const rec = b.id === recId;
        return (
          <div key={b.id} className={"tier-card" + (rec ? " recommended" : "") + (fits ? "" : " unfit")}>
            <div className="tier-card-h">
              <div className="tier-name mono">{b.name}</div>
              {rec ? <span className="tier-tag rec">★ recommended</span>
                   : fits ? <span className="tier-tag fit">fits</span>
                          : <span className="tier-tag unfit">needs ≥ {b.ram} GB</span>}
            </div>
            <div className="tier-spec">
              <b>{b.ram} GB+</b> unified · <b>~{b.sizeGB} GB</b> download
            </div>
            <div className="tier-stats">
              <div className="tier-stat">
                <div className="l">slots</div>
                <div className="v num">{b.includes.filter(i => i.active).length}<span className="u">/8</span></div>
              </div>
              <div className="tier-stat">
                <div className="l">size</div>
                <div className="v num">{b.sizeGB}<span className="u">GB</span></div>
              </div>
            </div>
            <div className="tier-includes">
              {b.includes.map((inc, i) => (
                <div key={i} className={"ln" + (inc.active ? "" : " faint")}>
                  <span className="ic">{inc.active ? "+" : "·"}</span>
                  <span>{inc.label}</span>
                </div>
              ))}
            </div>
            <div className="actions">
              <button className="btn" style={{flex: 1}} onClick={() => fits && onPick(b.id)} disabled={!fits}>
                Pick {b.name}
              </button>
            </div>
          </div>
        );
      })}
    </div>
  );
}

function BundleTable({ bundles, recId, onPick, ram }) {
  const rows = [
    { id: "chat",   label: "chat",   each: b => b.id === "lite" ? "1.2B" : b.id === "default" ? "9B" : b.id === "pro" ? "27B + 30B coder" : "35B + 30B coder + NPU 1B" },
    { id: "embed",  label: "embed + rerank", each: b => b.id === "lite" ? "—" : b.id === "default" ? "nomic-v1.5" : "nomic + bge-rerank" + (b.id === "max" ? " + embed-gemma" : "") },
    { id: "voice",  label: "voice (stt+tts)", each: b => b.id === "lite" ? "—" : b.id === "default" ? "whisper-base + kokoro" : "whisper-large + kokoro" + (b.id === "max" ? " + npu-stt" : "") },
    { id: "image",  label: "image",  each: b => b.id === "pro" ? "sd-turbo" : b.id === "max" ? "flux-2-klein-9b" : "—" },
    { id: "npu",    label: "NPU trio", each: b => b.id === "max" ? "agent + stt-npu + embed-npu" : "—" },
  ];
  return (
    <div className="card" style={{overflow: "hidden", marginBottom: 12}}>
      <div style={{display: "grid", gridTemplateColumns: "180px repeat(4, 1fr)", background: "var(--bg)", borderBottom: "1px solid var(--line)"}}>
        <div style={{padding: 14, fontFamily: "var(--jbm)", fontSize: 10, color: "var(--fg-4)", textTransform: "uppercase", letterSpacing: "0.1em"}}>capability</div>
        {bundles.map(b => {
          const fits = b.ram <= ram;
          const rec = b.id === recId;
          return (
            <div key={b.id} style={{padding: 14, borderLeft: "1px solid var(--line)", textAlign: "center", opacity: fits ? 1 : 0.5, position: "relative"}}>
              <div className="mono" style={{fontSize: 17, fontWeight: 500, letterSpacing: "-0.02em", color: rec ? "var(--accent)" : "var(--fg)"}}>{b.name}</div>
              <div className="mono" style={{fontSize: 10, color: "var(--fg-4)", marginTop: 2}}>{b.ram} GB+ · ~{b.sizeGB} GB</div>
              {rec && <div style={{position: "absolute", top: 0, left: 0, right: 0, height: 2, background: "var(--accent)"}} />}
            </div>
          );
        })}
      </div>
      {rows.map(r => (
        <div key={r.id} style={{display: "grid", gridTemplateColumns: "180px repeat(4, 1fr)", borderBottom: "1px solid var(--line-soft)"}}>
          <div style={{padding: 12, fontFamily: "var(--jbm)", fontSize: 12, color: "var(--fg-2)"}}>{r.label}</div>
          {bundles.map(b => {
            const v = r.each(b);
            const off = v === "—";
            return (
              <div key={b.id} style={{padding: 12, borderLeft: "1px solid var(--line-soft)", fontFamily: "var(--jbm)", fontSize: 11.5, textAlign: "center", color: off ? "var(--fg-5)" : "var(--fg-2)"}}>
                {v}
              </div>
            );
          })}
        </div>
      ))}
      <div style={{display: "grid", gridTemplateColumns: "180px repeat(4, 1fr)", borderTop: "1px solid var(--line)", background: "var(--bg)"}}>
        <div style={{padding: 12}} />
        {bundles.map(b => {
          const fits = b.ram <= ram;
          return (
            <div key={b.id} style={{padding: 12, borderLeft: "1px solid var(--line-soft)", textAlign: "center"}}>
              <button className="btn sm" style={{width: "92%", justifyContent: "center"}} disabled={!fits} onClick={() => fits && onPick(b.id)}>
                Pick {b.name}
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ─── Bundle confirmation (state 2) ───
function FirstRunConfirm({ bundleId, onBack, onInstall }) {
  const [withNpu, setWithNpu] = useStateF(false);
  // Phase B1: bundles + install mutation. Pull the install trigger
  // through the real hook; main.jsx's setFrStage('progress') still
  // drives the progress view.
  const bundlesQuery = useCuratedBundles();
  const installM = useFirstRunInstall();
  const bundles = bundlesQuery.data?.bundles ?? HAL0_DATA.bundles;
  const bundle = bundles.find(b => b.id === bundleId) || HAL0_DATA.bundles.find(b => b.id === bundleId);
  const det = HAL0_DATA.bundleDetails.pro; // detail-level data not yet over /api/firstrun
  return (
    <div className="fr-inner">
      <span className="fr-confirm-back mono" onClick={onBack}>← back to picker</span>
      <div className="fr-confirm-h">
        <h2>hal0-{bundle.name}</h2>
        <span className="sub">{bundle.ram} GB+ unified · ~{bundle.sizeGB} GB download · est 12 min</span>
      </div>
      <p className="fr-confirm-sub">{bundle.desc} You can change any slot after install.</p>

      <div className="fr-confirm-card">
        <div className="fr-confirm-card-h mono">
          <span>What gets installed</span>
          <b>{det.models.length} slots</b>
          <span style={{color: "var(--fg-4)"}}>· {det.models.reduce((a, m) => a + parseFloat(m.size), 0).toFixed(1)} GB total</span>
          <span className="right">capabilities.toml</span>
        </div>
        {det.models.map(m => (
          <div key={m.slot} className="fr-confirm-row">
            <span className="nm">{m.slot}</span>
            <span className="ml">{m.model}</span>
            <span className="sz">{m.size}</span>
            <span className="tag">
              {m.tag.split(" ").map((t, i) => <span key={i} className={"chip" + (t === "cpu" ? " dev-cpu" : t === "default" ? " amber outlined" : "")}>{t}</span>)}
            </span>
          </div>
        ))}
      </div>

      <div className="fr-confirm-card">
        <div className="fr-confirm-card-h mono" style={{justifyContent: "space-between"}}>
          <div style={{display: "flex", alignItems: "center", gap: 14}}>
            <span style={{display: "inline-flex", alignItems: "center", gap: 8}}>
              <span style={{width: 18, height: 18, borderRadius: 3, border: "1px solid rgba(200,150,255,0.40)", background: "rgba(200,150,255,0.08)", color: "var(--dev-npu)", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 9, letterSpacing: "0.05em", fontWeight: 600}}>NPU</span>
              FLM trio
            </span>
            <span style={{color: "var(--fg-4)"}}>· optional</span>
          </div>
          <label className="mono" style={{display: "inline-flex", alignItems: "center", gap: 8, cursor: "pointer", color: "var(--fg-2)"}}>
            <input type="checkbox" checked={withNpu} onChange={e => setWithNpu(e.target.checked)} style={{accentColor: "var(--accent)"}} />
            <span>Enable on install</span>
          </label>
        </div>
        {det.npu.map(m => (
          <div key={m.slot} className="fr-confirm-row" style={{opacity: withNpu ? 1 : 0.55}}>
            <span className="nm" style={{color: "var(--dev-npu)"}}>{m.slot}</span>
            <span className="ml">{m.model}</span>
            <span className="sz">{m.size}</span>
            <span className="tag">{m.tag.split(" ").map((t, i) => <span key={i} className="chip">{t}</span>)}</span>
          </div>
        ))}
        <div className="fr-confirm-foot">
          <span>~2 GB NPU memory · ~14s swap penalty on chat-model change · stt-npu + embed-npu are passengers</span>
        </div>
      </div>

      <div className="card" style={{padding: 16, fontSize: 12.5, color: "var(--fg-3)", marginBottom: 24, background: "var(--bg)"}}>
        <div className="mono" style={{fontSize: 10, color: "var(--fg-4)", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 8}}>Notes</div>
        <ul style={{margin: 0, paddingLeft: 18, lineHeight: 1.7}}>
          <li>TTS runs on CPU only on Linux (kokoro:cpu). ~1s per sentence.</li>
          <li><span className="mono" style={{color: "var(--fg-2)"}}>coder</span> slot is LRU-evictable — only one chat model is resident at a time when both exceed the per-type budget.</li>
          <li>HF_TOKEN is not required for this bundle. Configure later in Settings if you want gated repos.</li>
        </ul>
      </div>

      <div className="fr-actions">
        <button className="btn ghost lg" onClick={onBack}>Cancel</button>
        <button className="btn lg" onClick={() => {
          // Best-effort backend kick; UI advances regardless so the
          // mock build still shows the progress stage.
          installM.mutate({ bundle: bundleId, withNpu });
          onInstall();
        }}>{Icons.download} Install hal0-{bundle.name}</button>
      </div>
    </div>
  );
}

// ─── Install progress (state 3) ───
function FirstRunProgress({ onDone }) {
  // Phase B1: complete-mutation flips the backend's firstrun.completed
  // flag when the user clicks "Open dashboard". Downloads list is
  // intentionally still HAL0_DATA — per-row SSE wiring via
  // `usePullJob(id)` lands in B2 when DownloadRow swaps in the hook.
  const completeM = useFirstRunComplete();
  return (
    <div className="fr-inner">
      <div className="fr-prog-h">
        <h2>Installing hal0-Pro…</h2>
        <span className="meta">~38 GB total · est 12 min · downloads continue in background</span>
      </div>

      <div className="fr-prog-list">
        {HAL0_DATA.downloads.map((d, i) => (
          <div key={i} className="dl-row">
            <div className="dl-name mono">
              {d.name}
              <span className="sub">{d.repo}{d.rate && d.state === "pulling" ? ` · ${d.rate} · ${d.eta} remaining` : ""}</span>
            </div>
            <div className="dl-bar">
              <i className={d.state === "done" ? "ok" : d.state === "error" ? "err" : ""} style={{ width: `${d.pct}%` }} />
            </div>
            <div className={"dl-pct mono" + (d.state === "done" ? " ok" : d.state === "queued" ? " dim" : d.state === "error" ? " err" : "")}>
              {d.state === "done" ? "✓ 100%" : d.state === "queued" ? "queued" : d.state === "error" ? "✗ failed" : `${d.pct}%`}
            </div>
            <div className="dl-state mono">
              {d.state === "pulling" && `${d.done} / ${d.size}`}
              {d.state === "queued" && "waiting"}
              {d.state === "verifying" && "verifying"}
              {d.state === "done" && "complete"}
              {d.state === "paused" && "paused"}
              {d.state === "error" && "shard 2/2 sha256 mismatch"}
              {d.state === "cancelled" && "cancelled"}
            </div>
            {d.state === "error" && (
              <div className="dl-err">
                <span style={{color: "var(--err)", display: "inline-flex"}}>{Icons.warn}</span>
                <span style={{flex: 1}}>
                  <b>{d.name}</b> · corrupted shard 2 of 2 — sha256 mismatch. Retry to re-fetch the bad shard, or skip this model and pull it later from <span className="mono" style={{color: "var(--fg)"}}>/models</span>.
                </span>
                <button className="btn ghost sm" onClick={() => window.__hal0Toast && window.__hal0Toast(`Retrying ${d.name}`, "info")}>{Icons.restart} Retry</button>
                <button className="btn ghost sm" onClick={() => window.__hal0Toast && window.__hal0Toast(`Skipped ${d.name} — install later from /models`, "warn")}>Skip this model</button>
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="fr-actions" style={{justifyContent: "space-between"}}>
        <button className="btn ghost lg">Pause all</button>
        <div style={{display: "flex", gap: 12}}>
          <button className="btn ghost lg">View logs</button>
          <button className="btn lg" onClick={() => {
            completeM.mutate();
            onDone();
          }}>Open dashboard</button>
        </div>
      </div>
    </div>
  );
}

// ─── FirstRun view shell ───
function FirstRunView({ frStage, setFrStage, frBundle, setFrBundle, onComplete, layout }) {
  const [skipOpen, setSkipOpen] = useStateF(false);
  return (
    <div className="fr">
      {frStage === "pick" && (
        <FirstRunPicker
          onPick={b => { setFrBundle(b); setFrStage("confirm"); }}
          onSkip={() => setSkipOpen(true)}
          layout={layout}
        />
      )}
      {frStage === "confirm" && (
        <FirstRunConfirm
          bundleId={frBundle}
          onBack={() => setFrStage("pick")}
          onInstall={() => setFrStage("progress")}
        />
      )}
      {frStage === "progress" && (
        <FirstRunProgress onDone={() => onComplete()} />
      )}
      <SkipBundleDialog
        open={skipOpen}
        onCancel={() => setSkipOpen(false)}
        onConfirm={() => { setSkipOpen(false); onComplete(); }}
      />
    </div>
  );
}

Object.assign(window, { FirstRunView, FirstRunPicker, FirstRunConfirm, FirstRunProgress, BundleGrid, BundleTable });

// ui/src/views/FirstRun.vue
<script setup>
/**
 * FirstRun.vue — v2 bundle picker (slice #172).
 *
 * Replaces the v1 8-step linear wizard with the v0.3 design's
 * three-state machine (pick → confirm → progress).
 *
 * Source: /tmp/hal0-design/hal0-v2/project/dash/firstrun.jsx +
 * v0.3 css at /tmp/hal0-design-v3/dashboard.css (.fr-*, .tier-*, .dl-*).
 *
 * State + endpoint wiring lives in
 *   components/firstrun/useFirstRun.js
 * The view only sequences sub-components + wires the skip dialog +
 * conditional banner triggers.
 */
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useFirstRun } from '../components/firstrun/useFirstRun.js'
import { useTweaksStore } from '../stores/tweaks.js'
import { useBannerStore } from '../stores/banner.js'
import { resetFirstRunGuard } from '../router.js'
import Wordmark from '../components/Wordmark.vue'
import BannerStack from '../components/primitives/BannerStack.vue'
import BundleGrid from '../components/firstrun/BundleGrid.vue'
import BundleTable from '../components/firstrun/BundleTable.vue'
import InstallProgressRow from '../components/firstrun/InstallProgressRow.vue'
import SkipBundleDialog from '../components/firstrun/SkipBundleDialog.vue'

const router = useRouter()
const s      = useFirstRun()
const tweaks = useTweaksStore()
const banner = useBannerStore()

// Dialog state (local — does not belong in the composable since it
// only matters when the picker is visible).
const skipDialogOpen = ref(false)

// Layout: useTweaksStore.firstrunLayout ∈ { 'tiers' | 'wizard' }.
// 'tiers' = BundleGrid (default); 'wizard' = BundleTable (capability matrix).
const useMatrixLayout = computed(() => tweaks.firstrunLayout === 'wizard')

// ─── Banner triggers ─────────────────────────────────────────────
// The catalog entries live in stores/banner.js — we only show/dismiss
// them based on derived state. Don't ADD entries here.
watch(
  () => [s.isReEntered.value, s.ramTooLow.value, s.needsHfToken.value, s.view.value],
  () => {
    banner.toggle('fr-reentered', s.isReEntered.value && s.view.value === 'pick')
    banner.toggle('fr-ram-low',   s.ramTooLow.value   && s.view.value === 'pick')
    banner.toggle('hf-gated',     s.needsHfToken.value && s.view.value !== 'progress')
  },
  { immediate: true },
)

// ─── Skip flow ───────────────────────────────────────────────────
function openSkipDialog() { skipDialogOpen.value = true }
function cancelSkip()     { skipDialogOpen.value = false }
async function confirmSkip() {
  skipDialogOpen.value = false
  // Skip = mark install complete and route to /. Per the design spec,
  // the dashboard shows configure-buttons on the seeded slots.
  await s.markComplete()
  resetFirstRunGuard()
  router.push('/')
}

// ─── Progress → completion ───────────────────────────────────────
// When every row settles to terminal (done|failed) we don't auto-route
// — the user clicks "Open dashboard". We DO mark install complete + flip
// the post-install hero state once they navigate away.
async function openDashboard() {
  await s.markComplete()
  resetFirstRunGuard()
  // Light flag the dashboard can pick up to render a one-shot
  // "✓ Installed" hero. Cleared by /views/Dashboard.vue on first read.
  try { window.sessionStorage.setItem('hal0:firstrun:just-installed', '1') } catch { /* private mode */ }
  router.push('/')
}

// Auto-dismiss firstrun banners on unmount so other views don't see
// stale picker-scoped chrome.
onMounted(() => { /* state machine already mounted by useFirstRun() */ })
onUnmounted(() => {
  banner.dismiss('fr-reentered')
  banner.dismiss('fr-ram-low')
  banner.dismiss('hf-gated')
  s.dispose()
})

// ─── Detected-hardware copy ──────────────────────────────────────
const detectLine = computed(() => {
  const parts = []
  if (s.ramGb.value > 0) parts.push(`${s.ramGb.value} GB RAM`)
  if (s.gpuLabel.value && s.gpuLabel.value !== '—') parts.push(s.gpuLabel.value)
  if (s.npuPresent.value) parts.push('NPU')
  return parts.length ? `Detected: ${parts.join(' · ')}` : ''
})

// Toggle the NPU opt-in on the confirm card. v-model on a child
// produces a deep-tree warning when the parent stores it; bind via
// the composable's reactive ref directly.
function toggleNpu(e) { s.withNpu.value = e.target.checked }
</script>

<template>
  <div class="fr">
    <!-- Banner stack (scope=firstrun + global) -->
    <div class="fr-banners">
      <BannerStack scope="firstrun" />
    </div>

    <div class="fr-inner">
      <!-- ─── STATE: PICK ──────────────────────────────────────── -->
      <template v-if="s.view.value === 'pick'">
        <div class="fr-head">
          <div class="fr-eyebrow">
            <span class="blip" />FirstRun · install
          </div>
          <Wordmark size="text-5xl" class="fr-wordmark" aria-hidden="true" />
          <h1 class="fr-title">Welcome to <span class="accent">hal0</span></h1>
          <p class="fr-lede">
            Pick a starting configuration. You can customise any slot later —
            or skip and configure manually.
          </p>
          <div v-if="detectLine" class="fr-detect" data-testid="fr-detect">
            <span class="seg" v-if="s.ramGb.value">
              <span class="k">RAM</span><b>{{ s.ramGb.value }} GB</b>
            </span>
            <span class="seg" v-if="s.gpuLabel.value && s.gpuLabel.value !== '—'">
              <span class="k">GPU</span><b>{{ s.gpuLabel.value }}</b>
            </span>
            <span class="seg" v-if="s.npuPresent.value">
              <span class="k">NPU</span><b>detected</b><span class="ok">●</span>
            </span>
            <span class="seg" v-if="s.diskFreeGb.value">
              <span class="k">disk</span><b>{{ s.diskFreeGb.value }} GB</b> free
            </span>
          </div>
        </div>

        <div v-if="s.loading.value" class="fr-loading mono">Probing hardware…</div>

        <template v-else>
          <!-- Layout variants — flipped via useTweaksStore.firstrunLayout -->
          <BundleGrid
            v-if="!useMatrixLayout"
            :bundles="s.bundles.value"
            @pick="s.pickBundle"
          />
          <BundleTable
            v-else
            :bundles="s.bundles.value"
            :ram-gb="s.ramGb.value"
            @pick="s.pickBundle"
          />

          <!-- Pre-built kits (only when host ≥100 GB RAM) -->
          <template v-if="s.ramGb.value >= 100">
            <h3 class="fr-section-label">Pre-built kits</h3>
            <div class="kit" data-testid="lmx-kit">
              <div class="kit-main">
                <div class="kit-eyebrow">AMD-curated · vendor-blessed</div>
                <div class="kit-name">LMX-Omni-52B-Halo</div>
                <div class="kit-spec">
                  ≥ 100 GB unified RAM Strix Halo · NPU trio · 4 slots ready out of the box
                </div>
                <div class="kit-models">
                  <span class="chip">Qwen3.6-35B</span>
                  <span class="chip">Whisper-Large</span>
                  <span class="chip">kokoro</span>
                  <span class="chip">Flux-2-Klein-9B</span>
                </div>
              </div>
              <div class="kit-side">
                <div class="sz mono">~75<span class="u">GB</span></div>
                <button type="button" class="btn lg" @click="s.pickBundle('max')">Install LMX kit</button>
              </div>
            </div>
          </template>

          <div class="fr-skip-row">
            <button
              type="button"
              class="fr-skip"
              data-testid="fr-skip"
              @click="openSkipDialog"
            >Skip — configure manually</button>
          </div>
        </template>
      </template>

      <!-- ─── STATE: CONFIRM ──────────────────────────────────── -->
      <template v-else-if="s.view.value === 'confirm' && s.currentBundle.value">
        <span
          class="fr-confirm-back mono"
          role="button"
          tabindex="0"
          data-testid="fr-confirm-back"
          @click="s.backToPicker"
          @keydown.enter="s.backToPicker"
        >← back to picker</span>

        <div class="fr-confirm-h">
          <h2>hal0-{{ s.currentBundle.value.name }}</h2>
          <span class="sub">
            {{ s.currentBundle.value.ram }} GB+ unified ·
            ~{{ s.currentBundle.value.sizeGB }} GB download ·
            est {{ Math.max(2, Math.round(s.currentBundle.value.sizeGB / 3)) }} min
          </span>
        </div>
        <p class="fr-confirm-sub">{{ s.currentBundle.value.desc }} You can change any slot after install.</p>

        <!-- Per-slot install list -->
        <div class="fr-confirm-card" data-testid="fr-install-list">
          <div class="fr-confirm-card-h mono">
            <span>What gets installed</span>
            <b>{{ s.currentDetails.value?.models.length || 0 }} slots</b>
            <span style="color: var(--fg-4)">· ~{{ s.aggregateSizeGb.value.toFixed(1) }} GB total</span>
            <span class="right">capabilities.toml</span>
          </div>
          <div
            v-for="row in s.currentDetails.value?.models || []"
            :key="row.slot"
            class="fr-confirm-row"
            :data-slot="row.slot"
          >
            <span class="nm">{{ row.slot }}</span>
            <span class="ml">{{ row.model }}</span>
            <span class="sz">{{ row.size }}</span>
            <span class="tag">
              <span
                v-for="(t, i) in row.tag.split(' ')"
                :key="i"
                class="chip"
                :class="{
                  'chip-amber-outlined': t === 'default',
                  'chip-cpu': t === 'cpu',
                }"
              >{{ t }}</span>
            </span>
          </div>
        </div>

        <!-- Optional NPU trio toggle (only when NPU detected + tier has NPU rows) -->
        <div
          v-if="s.npuPresent.value && (s.currentDetails.value?.npu?.length || 0) > 0"
          class="fr-confirm-card"
          data-testid="fr-npu-card"
        >
          <div class="fr-confirm-card-h mono" style="justify-content: space-between">
            <div style="display: flex; align-items: center; gap: 14px">
              <span class="npu-chip">NPU</span>
              <span>FLM trio</span>
              <span style="color: var(--fg-4)">· optional</span>
            </div>
            <label class="npu-toggle mono">
              <input
                type="checkbox"
                :checked="s.withNpu.value"
                data-testid="fr-npu-toggle"
                @change="toggleNpu"
              />
              <span>Enable on install</span>
            </label>
          </div>
          <div
            v-for="row in s.currentDetails.value?.npu || []"
            :key="row.slot"
            class="fr-confirm-row"
            :class="{ 'fr-confirm-row-faint': !s.withNpu.value }"
            :data-npu-slot="row.slot"
          >
            <span class="nm npu">{{ row.slot }}</span>
            <span class="ml">{{ row.model }}</span>
            <span class="sz">{{ row.size }}</span>
            <span class="tag">
              <span v-for="(t, i) in row.tag.split(' ')" :key="i" class="chip">{{ t }}</span>
            </span>
          </div>
          <div class="fr-confirm-foot">
            <span>~2 GB NPU memory · ~14s swap penalty on chat-model change · stt-npu + embed-npu are passengers</span>
          </div>
        </div>

        <!-- Notes — license + HF_TOKEN warning -->
        <div class="card notes-card">
          <div class="notes-h mono">Notes</div>
          <ul class="notes-ul">
            <li>By installing, you accept each model's upstream license. hal0 does not redistribute weights — files come straight from Hugging Face.</li>
            <li v-if="s.needsHfToken.value" class="notes-warn">
              One or more models are gated on Hugging Face. Set <span class="mono">HF_TOKEN</span> in
              <strong>Settings → Storage</strong> before install, or this bundle will fail to pull.
            </li>
            <li v-else>HF_TOKEN is not required for this bundle. Configure later in Settings to enable gated repos.</li>
            <li v-if="!s.fitsDisk.value" class="notes-err">
              Not enough disk: needs ~{{ s.aggregateSizeGb.value.toFixed(1) }} GB,
              only {{ s.diskFreeGb.value }} GB free on first model dir.
            </li>
          </ul>
        </div>

        <div class="fr-actions">
          <button type="button" class="btn ghost lg" @click="s.backToPicker">Cancel</button>
          <button
            type="button"
            class="btn lg"
            data-testid="fr-install-btn"
            :disabled="!s.fitsDisk.value"
            @click="s.startInstall"
          >Install hal0-{{ s.currentBundle.value.name }}</button>
        </div>
      </template>

      <!-- ─── STATE: PROGRESS ─────────────────────────────────── -->
      <template v-else-if="s.view.value === 'progress'">
        <div class="fr-prog-h">
          <h2>
            <template v-if="s.pull.done && !s.pull.error">✓ Installed</template>
            <template v-else>Installing hal0-{{ s.currentBundle.value?.name }}…</template>
          </h2>
          <span class="meta">
            ~{{ s.aggregateSizeGb.value.toFixed(1) }} GB total · downloads continue in background
          </span>
        </div>

        <div class="fr-prog-list" data-testid="fr-prog-list">
          <InstallProgressRow
            v-for="item in s.pull.items"
            :key="item.key"
            :item="item"
            @retry="s.retryItem"
            @skip="s.skipItem"
          />
        </div>

        <div v-if="s.pull.error" class="fr-prog-err mono">{{ s.pull.error }}</div>

        <div class="fr-actions" style="justify-content: space-between">
          <button
            type="button"
            class="btn ghost lg"
            :disabled="s.pull.done"
            data-testid="fr-pause-all"
            @click="s.pauseAll"
          >Pause all</button>
          <button
            type="button"
            class="btn lg"
            data-testid="fr-open-dashboard"
            @click="openDashboard"
          >Open dashboard</button>
        </div>
      </template>
    </div>

    <!-- Skip confirm dialog (always present, opens on demand) -->
    <SkipBundleDialog
      :open="skipDialogOpen"
      :on-cancel="cancelSkip"
      :on-confirm="confirmSkip"
    />
  </div>
</template>

<style scoped>
.fr {
  min-height: calc(100vh - var(--topbar-h, 0px) - var(--footer-h, 0px));
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 56px 32px 80px;
  background: var(--bg);
}
.fr-banners { width: 100%; max-width: 1240px; }
.fr-inner   { width: 100%; max-width: 1240px; }
.fr-loading { padding: 48px; text-align: center; color: var(--fg-3); font-size: 13px; }

/* ─── PICK state ─────────────────────────────────────────────── */
.fr-head { text-align: center; margin-bottom: 48px; }
.fr-eyebrow {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 4px 10px;
  border: 1px solid var(--accent-line);
  background: var(--accent-soft);
  border-radius: 999px;
  font-family: var(--jbm);
  font-size: 10px;
  color: var(--accent);
  text-transform: uppercase;
  letter-spacing: 0.1em;
  margin-bottom: 22px;
}
.fr-eyebrow .blip {
  width: 5px; height: 5px; background: var(--accent); border-radius: 50%;
  animation: fr-pulse 1.5s ease-in-out infinite;
}
@keyframes fr-pulse {
  0%, 100% { opacity: 1; }
  50%      { opacity: 0.4; }
}
.fr-wordmark { display: flex; justify-content: center; margin: 0 auto 18px; }
.fr-title {
  font-family: var(--jbm);
  font-weight: 500;
  font-size: clamp(36px, 4vw, 52px);
  letter-spacing: -0.03em;
  line-height: 1.05;
  margin: 0 0 16px;
}
.fr-title .accent { color: var(--accent); }
.fr-lede {
  font-size: 16px;
  color: var(--fg-2);
  max-width: 620px;
  margin: 0 auto 22px;
  line-height: 1.55;
  text-wrap: pretty;
}

.fr-detect {
  display: inline-flex;
  flex-wrap: wrap;
  font-family: var(--jbm);
  font-size: 12px;
  color: var(--fg-3);
  border: 1px solid var(--line);
  border-radius: var(--rad);
  background: var(--bg-1);
  overflow: hidden;
}
.fr-detect .seg {
  padding: 7px 14px;
  border-right: 1px solid var(--line-soft);
  display: inline-flex;
  align-items: center;
  gap: 8px;
}
.fr-detect .seg:last-child { border-right: none; }
.fr-detect .seg .k { color: var(--fg-5); }
.fr-detect .seg b  { color: var(--fg); font-weight: 500; }
.fr-detect .ok     { color: var(--ok); }

.fr-section-label {
  font-family: var(--jbm);
  font-size: 11px;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: var(--fg-4);
  margin: 28px 0 16px;
  display: flex;
  align-items: center;
  gap: 16px;
}
.fr-section-label::after { content: ''; flex: 1; height: 1px; background: var(--line-soft); }

/* LMX kit */
.kit {
  background: linear-gradient(135deg, var(--bg-1) 0%, color-mix(in oklab, var(--accent-soft) 30%, var(--bg-1)) 100%);
  border: 1px solid var(--accent-line);
  border-radius: var(--rad-lg);
  padding: 24px 28px;
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 24px;
  align-items: center;
  margin-bottom: 40px;
  position: relative;
  overflow: hidden;
}
.kit::before {
  content: ''; position: absolute; inset: 0;
  background: radial-gradient(circle at 80% 50%, var(--accent-soft), transparent 60%);
  pointer-events: none;
}
.kit-main { position: relative; }
.kit-eyebrow { font-family: var(--jbm); font-size: 10px; color: var(--accent); text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 8px; }
.kit-name { font-family: var(--jbm); font-size: 22px; font-weight: 500; letter-spacing: -0.02em; margin-bottom: 8px; }
.kit-spec { font-family: var(--jbm); font-size: 12px; color: var(--fg-3); margin-bottom: 12px; }
.kit-models { display: flex; flex-wrap: wrap; gap: 6px; }
.kit-side { position: relative; text-align: right; display: flex; flex-direction: column; gap: 8px; align-items: flex-end; }
.kit-side .sz { font-family: var(--jbm); font-size: 24px; font-weight: 500; color: var(--fg); letter-spacing: -0.02em; }
.kit-side .sz .u { color: var(--accent); font-size: 14px; margin-left: 2px; }

.fr-skip-row { display: flex; justify-content: center; gap: 24px; align-items: center; margin-top: 16px; }
.fr-skip {
  background: transparent;
  border: none;
  font-family: var(--jbm);
  font-size: 12px;
  color: var(--fg-3);
  cursor: pointer;
  padding: 6px 12px;
  border-bottom: 1px dashed var(--line);
}
.fr-skip:hover { color: var(--accent); border-color: var(--accent-line); }

/* ─── CONFIRM state ──────────────────────────────────────────── */
.fr-confirm-back {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-family: var(--jbm);
  font-size: 12px;
  color: var(--fg-3);
  cursor: pointer;
  margin-bottom: 20px;
  outline: none;
}
.fr-confirm-back:hover, .fr-confirm-back:focus-visible { color: var(--accent); }

.fr-confirm-h { display: flex; align-items: baseline; gap: 14px; margin-bottom: 6px; }
.fr-confirm-h h2 { font-family: var(--jbm); font-size: 32px; font-weight: 500; margin: 0; letter-spacing: -0.025em; }
.fr-confirm-h .sub { font-family: var(--jbm); font-size: 13px; color: var(--fg-3); }
.fr-confirm-sub { font-family: var(--jbm); font-size: 12px; color: var(--fg-3); margin-bottom: 28px; }

.fr-confirm-card {
  border: 1px solid var(--line);
  border-radius: var(--rad-lg);
  background: var(--bg-1);
  overflow: hidden;
  margin-bottom: 20px;
}
.fr-confirm-card-h {
  padding: 14px 18px;
  border-bottom: 1px solid var(--line);
  display: flex;
  align-items: center;
  gap: 14px;
  font-family: var(--jbm);
  font-size: 12px;
  color: var(--fg-3);
  background: var(--bg);
}
.fr-confirm-card-h b { color: var(--fg); font-weight: 500; }
.fr-confirm-card-h .right { margin-left: auto; }

.fr-confirm-row {
  display: grid;
  grid-template-columns: 100px 1fr 120px 120px;
  gap: 14px;
  align-items: center;
  padding: 11px 18px;
  border-bottom: 1px solid var(--line-soft);
  font-family: var(--jbm);
  font-size: 12px;
}
.fr-confirm-row:last-child { border-bottom: none; }
.fr-confirm-row .nm { color: var(--accent); }
.fr-confirm-row .nm.npu { color: var(--dev-npu, #c896ff); }
.fr-confirm-row .ml { color: var(--fg); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.fr-confirm-row .sz { color: var(--fg-2); text-align: right; }
.fr-confirm-row .tag { color: var(--fg-3); text-align: right; display: flex; gap: 5px; justify-content: flex-end; }
.fr-confirm-row-faint { opacity: 0.55; }

.fr-confirm-foot {
  padding: 14px 18px;
  background: var(--bg);
  border-top: 1px solid var(--line);
  font-family: var(--jbm);
  font-size: 11px;
  color: var(--fg-4);
  display: flex;
  align-items: center;
  gap: 10px;
}

.npu-chip {
  width: 28px; height: 18px;
  border-radius: 3px;
  border: 1px solid rgba(200, 150, 255, 0.40);
  background: rgba(200, 150, 255, 0.08);
  color: var(--dev-npu, #c896ff);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-size: 9px;
  letter-spacing: 0.05em;
  font-weight: 600;
}
.npu-toggle {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  color: var(--fg-2);
}
.npu-toggle input { accent-color: var(--accent); }

.notes-card {
  padding: 16px;
  font-size: 12.5px;
  color: var(--fg-3);
  margin-bottom: 24px;
  background: var(--bg);
  border: 1px solid var(--line);
  border-radius: var(--rad-lg);
}
.notes-h {
  font-size: 10px;
  color: var(--fg-4);
  text-transform: uppercase;
  letter-spacing: 0.1em;
  margin-bottom: 8px;
}
.notes-ul { margin: 0; padding-left: 18px; line-height: 1.7; }
.notes-warn { color: var(--warn); }
.notes-err  { color: var(--err); }
.notes-ul .mono { font-family: var(--jbm); color: var(--fg-2); }

.fr-actions {
  display: flex;
  gap: 12px;
  justify-content: flex-end;
  padding-top: 12px;
}

/* ─── PROGRESS state ─────────────────────────────────────────── */
.fr-prog-h {
  display: flex;
  align-items: baseline;
  gap: 14px;
  margin-bottom: 22px;
}
.fr-prog-h h2 {
  font-family: var(--jbm);
  font-size: 28px;
  font-weight: 500;
  margin: 0;
  letter-spacing: -0.025em;
}
.fr-prog-h .meta { font-family: var(--jbm); font-size: 12px; color: var(--fg-3); }

.fr-prog-list {
  border: 1px solid var(--line);
  border-radius: var(--rad-lg);
  background: var(--bg-1);
  overflow: hidden;
  margin-bottom: 22px;
}

.fr-prog-err {
  margin-bottom: 16px;
  padding: 10px 14px;
  border: 1px solid var(--err-line);
  background: var(--err-soft);
  border-radius: var(--rad);
  color: var(--err);
  font-size: 12px;
}

/* ─── Chip shim (until /primitives is reachable from this scope) ─── */
.chip {
  display: inline-flex;
  align-items: center;
  padding: 1px 6px;
  border-radius: 3px;
  background: var(--bg-3);
  color: var(--fg-3);
  font-family: var(--jbm);
  font-size: 10px;
  letter-spacing: 0.04em;
  border: 1px solid var(--line);
}
.chip-amber-outlined { color: var(--accent); border-color: var(--accent-line); background: transparent; }
.chip-cpu { color: var(--fg-3); }
</style>
